import { Product } from './types'

export const categories = [
  'Todos',
  'Laptops Gaming',
  'Perifericos',
  'Consolas',
  'Componentes PC',
  'Celulares',
] as const

export type Category = (typeof categories)[number]

export const provinces = [
  'Buenos Aires',
  'Ciudad Autonoma de Buenos Aires',
  'Catamarca',
  'Chaco',
  'Chubut',
  'Cordoba',
  'Corrientes',
  'Entre Rios',
  'Formosa',
  'Jujuy',
  'La Pampa',
  'La Rioja',
  'Mendoza',
  'Misiones',
  'Neuquen',
  'Rio Negro',
  'Salta',
  'San Juan',
  'San Luis',
  'Santa Cruz',
  'Santa Fe',
  'Santiago del Estero',
  'Tierra del Fuego',
  'Tucuman',
]

export const products: Product[] = [
  // Laptops Gaming
  {
    id: 'laptop-1',
    name: 'ASUS ROG Strix G16',
    price: 1899999,
    category: 'Laptops Gaming',
    image: '/products/laptop-1.jpg',
    description: 'Intel Core i7-13650HX, RTX 4060, 16GB DDR5, 512GB SSD, 16" FHD 165Hz',
  },
  {
    id: 'laptop-2',
    name: 'Lenovo Legion 5 Pro',
    price: 2199999,
    category: 'Laptops Gaming',
    image: '/products/laptop-2.jpg',
    description: 'AMD Ryzen 7 7745HX, RTX 4070, 16GB DDR5, 1TB SSD, 16" WQXGA 165Hz',
  },
  {
    id: 'laptop-3',
    name: 'MSI Katana 15',
    price: 1299999,
    category: 'Laptops Gaming',
    image: '/products/laptop-3.jpg',
    description: 'Intel Core i7-13620H, RTX 4050, 16GB DDR5, 512GB SSD, 15.6" FHD 144Hz',
  },
  {
    id: 'laptop-4',
    name: 'Acer Nitro V 15',
    price: 1099999,
    category: 'Laptops Gaming',
    image: '/products/laptop-4.jpg',
    description: 'Intel Core i5-13420H, RTX 4050, 16GB DDR5, 512GB SSD, 15.6" FHD 144Hz',
  },
  {
    id: 'laptop-5',
    name: 'HP Victus 16',
    price: 1499999,
    category: 'Laptops Gaming',
    image: '/products/laptop-5.jpg',
    description: 'AMD Ryzen 7 7840HS, RTX 4060, 16GB DDR5, 512GB SSD, 16.1" FHD 144Hz',
  },

  // Perifericos
  {
    id: 'perif-1',
    name: 'Logitech G Pro X Superlight 2',
    price: 189999,
    category: 'Perifericos',
    image: '/products/perif-1.jpg',
    description: 'Mouse gaming inalambrico, sensor HERO 2, 44.000 DPI, 60g ultraliviano',
  },
  {
    id: 'perif-2',
    name: 'HyperX Cloud III Wireless',
    price: 159999,
    category: 'Perifericos',
    image: '/products/perif-2.jpg',
    description: 'Auriculares gaming inalambricos, DTS Spatial Audio, 120hs de bateria',
  },
  {
    id: 'perif-3',
    name: 'Razer Huntsman V3 Pro',
    price: 279999,
    category: 'Perifericos',
    image: '/products/perif-3.jpg',
    description: 'Teclado mecanico analogico, switches opticos, PBT keycaps, RGB por tecla',
  },
  {
    id: 'perif-4',
    name: 'SteelSeries Arctis Nova Pro',
    price: 349999,
    category: 'Perifericos',
    image: '/products/perif-4.jpg',
    description: 'Auriculares premium, ANC activo, DAC GameDAC Gen 2, Hi-Res Audio',
  },
  {
    id: 'perif-5',
    name: 'Corsair K70 RGB Pro',
    price: 219999,
    category: 'Perifericos',
    image: '/products/perif-5.jpg',
    description: 'Teclado mecanico Cherry MX Red, marco de aluminio, RGB por tecla, USB passthrough',
  },

  // Consolas
  {
    id: 'consola-1',
    name: 'PlayStation 5 Slim',
    price: 899999,
    category: 'Consolas',
    image: '/products/consola-1.jpg',
    description: 'Consola PS5 Slim con lectora, 1TB SSD, DualSense incluido, 4K HDR',
  },
  {
    id: 'consola-2',
    name: 'Xbox Series X',
    price: 849999,
    category: 'Consolas',
    image: '/products/consola-2.jpg',
    description: 'Consola Xbox Series X 1TB SSD, 4K a 120fps, Xbox Game Pass compatible',
  },
  {
    id: 'consola-3',
    name: 'Nintendo Switch OLED',
    price: 599999,
    category: 'Consolas',
    image: '/products/consola-3.jpg',
    description: 'Pantalla OLED 7 pulgadas, 64GB almacenamiento, Joy-Con incluidos, dock HDMI',
  },
  {
    id: 'consola-4',
    name: 'PlayStation 5 Digital',
    price: 749999,
    category: 'Consolas',
    image: '/products/consola-4.jpg',
    description: 'Consola PS5 Digital Edition, 1TB SSD, sin lectora de discos, DualSense incluido',
  },
  {
    id: 'consola-5',
    name: 'Xbox Series S',
    price: 449999,
    category: 'Consolas',
    image: '/products/consola-5.jpg',
    description: 'Consola compacta all-digital, 512GB SSD, 1440p a 120fps, Game Pass Ready',
  },

  // Componentes PC
  {
    id: 'comp-1',
    name: 'NVIDIA GeForce RTX 4070 Ti Super',
    price: 1599999,
    category: 'Componentes PC',
    image: '/products/comp-1.jpg',
    description: 'GPU 16GB GDDR6X, DLSS 3, Ray Tracing, PCIe 4.0, ideal para 1440p y 4K',
  },
  {
    id: 'comp-2',
    name: 'AMD Ryzen 7 7800X3D',
    price: 649999,
    category: 'Componentes PC',
    image: '/products/comp-2.jpg',
    description: 'Procesador gaming 8 nucleos/16 hilos, 3D V-Cache, AM5, el mejor para gaming',
  },
  {
    id: 'comp-3',
    name: 'Corsair Vengeance DDR5 32GB',
    price: 189999,
    category: 'Componentes PC',
    image: '/products/comp-3.jpg',
    description: 'Kit 2x16GB DDR5-6000MHz, CL36, XMP 3.0, RGB, optimizado para AM5',
  },
  {
    id: 'comp-4',
    name: 'Samsung 990 PRO 2TB NVMe',
    price: 349999,
    category: 'Componentes PC',
    image: '/products/comp-4.jpg',
    description: 'SSD NVMe M.2 PCIe 4.0, lectura 7.450MB/s, escritura 6.900MB/s, con disipador',
  },
  {
    id: 'comp-5',
    name: 'ASUS ROG Strix B650E-F',
    price: 449999,
    category: 'Componentes PC',
    image: '/products/comp-5.jpg',
    description: 'Motherboard AM5, DDR5, PCIe 5.0, WiFi 6E, USB4, iluminacion Aura Sync RGB',
  },

  // Celulares
  {
    id: 'celular-1',
    name: 'Samsung Galaxy S24 Ultra',
    price: 1899999,
    category: 'Celulares',
    image: '/products/celular-1.jpg',
    description: 'Snapdragon 8 Gen 3, 12GB RAM, 256GB, pantalla AMOLED 6.8" QHD+ 120Hz, S Pen, Galaxy AI',
  },
  {
    id: 'celular-2',
    name: 'iPhone 15 Pro Max',
    price: 2299999,
    category: 'Celulares',
    image: '/products/celular-2.jpg',
    description: 'Chip A17 Pro, 256GB, titanio natural, camara 48MP 5x zoom, USB-C, Action Button',
  },
  {
    id: 'celular-3',
    name: 'Xiaomi 14 Ultra',
    price: 1599999,
    category: 'Celulares',
    image: '/products/celular-3.jpg',
    description: 'Snapdragon 8 Gen 3, 16GB RAM, 512GB, camara Leica Summilux 50MP, carga 90W',
  },
  {
    id: 'celular-4',
    name: 'Motorola Edge 50 Ultra',
    price: 1199999,
    category: 'Celulares',
    image: '/products/celular-4.jpg',
    description: 'Snapdragon 8s Gen 3, 16GB RAM, 1TB, pantalla pOLED 6.7" 144Hz, 50MP OIS',
  },
  {
    id: 'celular-5',
    name: 'Google Pixel 8 Pro',
    price: 1399999,
    category: 'Celulares',
    image: '/products/celular-5.jpg',
    description: 'Tensor G3, 12GB RAM, 256GB, camara 50MP con Magic Eraser, 7 anos de updates',
  },
]

export const offers: Product[] = [
  {
    id: 'oferta-1',
    name: 'Razer DeathAdder V3',
    price: 89999,
    originalPrice: 139999,
    category: 'Perifericos',
    image: '/products/oferta-1.jpg',
    description: 'Mouse gaming ergonomico, sensor Focus Pro 30K, 59g, switches opticos Gen-3',
    isOffer: true,
    discount: 36,
  },
  {
    id: 'oferta-2',
    name: 'MSI MAG B760M Mortar WiFi',
    price: 199999,
    originalPrice: 289999,
    category: 'Componentes PC',
    image: '/products/oferta-2.jpg',
    description: 'Motherboard Intel LGA 1700, DDR5, PCIe 4.0, WiFi 6E, 2.5G LAN',
    isOffer: true,
    discount: 31,
  },
  {
    id: 'oferta-3',
    name: 'Kingston Fury Beast DDR5 16GB',
    price: 79999,
    originalPrice: 119999,
    category: 'Componentes PC',
    image: '/products/oferta-3.jpg',
    description: 'Memoria DDR5-5600MHz, CL40, 1x16GB, XMP 3.0, disipador de aluminio',
    isOffer: true,
    discount: 33,
  },
  {
    id: 'oferta-4',
    name: 'Logitech G435 Lightspeed',
    price: 69999,
    originalPrice: 109999,
    category: 'Perifericos',
    image: '/products/oferta-4.jpg',
    description: 'Auriculares inalambricos, Bluetooth + Lightspeed, 165g ultralivianos, 18hs bateria',
    isOffer: true,
    discount: 36,
  },
]

export function formatPrice(price: number): string {
  return new Intl.NumberFormat('es-AR', {
    style: 'currency',
    currency: 'ARS',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price)
}
